# Generated by Django 4.2 on 2023-05-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('short_text', models.CharField(max_length=250, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('photo', models.CharField(max_length=250, verbose_name='Фото: номер записи')),
                ('tag_firefox', models.BooleanField(default=0, verbose_name='Tag_Fierfox')),
                ('tag_Opera', models.BooleanField(default=0, verbose_name='Tag_Opera')),
                ('tag_tarifs', models.BooleanField(default=0, verbose_name='Tag_Tarifs')),
                ('tag_multiport', models.BooleanField(default=0, verbose_name='Tag_multiport')),
                ('categories_arbitraj', models.BooleanField(default=0, verbose_name='Fierfox')),
                ('categories_nocontent', models.BooleanField(default=0, verbose_name='Без рубрики')),
                ('categories_mobileproxy', models.BooleanField(default=0, verbose_name='Мобильные прокси')),
                ('categories_settingsproxy', models.BooleanField(default=0, verbose_name='Настройки прокси')),
                ('categories_aboutproxy', models.BooleanField(default=0, verbose_name='О прокси')),
                ('categories_moneysystem', models.BooleanField(default=0, verbose_name='Платёжные системы')),
                ('categories_tarifs', models.BooleanField(default=0, verbose_name='Тарифы')),
                ('include_templates', models.CharField(max_length=250, verbose_name='Название шаблона')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
    ]
