# Generated by Django 4.2 on 2023-05-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='short_text',
            field=models.CharField(max_length=250, verbose_name='Текст'),
        ),
    ]
