# Generated by Django 4.2 on 2023-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_news_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag_yandex',
            field=models.BooleanField(default=0, verbose_name='Tag_yandex'),
        ),
    ]
