# Generated by Django 4.2 on 2023-05-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_news_tag_yandex'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='code',
            field=models.CharField(default='none', max_length=250, verbose_name='Название в коде'),
        ),
        migrations.AddField(
            model_name='tags',
            name='code',
            field=models.CharField(default='none', max_length=250, verbose_name='Название в коде'),
        ),
    ]
