# Generated by Django 4.2 on 2023-05-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_categories_code_tags_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
