# Generated by Django 4.2 on 2023-05-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_news_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='view',
        ),
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='blog.ip'),
        ),
    ]
