# Generated by Django 4.2 on 2023-05-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_ip_remove_news_view_news_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view',
        ),
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.IntegerField(default=0, verbose_name='post_views'),
        ),
    ]
