# Generated by Django 4.2 on 2023-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_news_view_news_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view',
        ),
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='blog.ip'),
        ),
    ]
