# Generated by Django 4.2 on 2023-05-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_news_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='blog.ip'),
        ),
    ]
