# Generated by Django 4.2 on 2023-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_news_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view',
        ),
        migrations.AddField(
            model_name='news',
            name='view_set',
            field=models.ManyToManyField(blank=True, related_name='views', to='blog.ip'),
        ),
    ]
