# Generated by Django 4.2 on 2023-05-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_view_set_news_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view',
        ),
    ]
