# Generated by Django 4.2 on 2023-05-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_news_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.ip'),
        ),
    ]
