# Generated by Django 4.2 on 2023-05-18 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_news_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='view',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.ip'),
        ),
    ]
