# Generated by Django 4.2 on 2023-05-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_news_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='view',
            field=models.ManyToManyField(to='blog.ip'),
        ),
    ]
