# Generated by Django 4.2 on 2023-05-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_news_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='view',
            field=models.ManyToManyField(related_name='view_id', to='blog.ip'),
        ),
    ]
