# Generated by Django 4.2 on 2023-05-18 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_news_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view',
        ),
        migrations.DeleteModel(
            name='Ip',
        ),
    ]
