# Generated by Django 4.2 on 2023-05-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_news_id_remove_news_view_news_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='view',
            new_name='view_id',
        ),
    ]
