# Generated by Django 4.2 on 2023-05-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_news_view_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_id',
        ),
    ]
