# Generated by Django 4.2 on 2023-05-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_news_view_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='view_id',
        ),
        migrations.AddField(
            model_name='news',
            name='view_id',
            field=models.ManyToManyField(blank=True, related_name='views', to='blog.ip'),
        ),
    ]
